pipeline {
 agent any
 environment {
  dotnet = 'C:\\Program Files\\dotnet\\dotnet.exe'
 }
 stages {
  stage('Checkout') {
   steps {
    git credentialsId: 'none',
    url: 'https://github.com/RiyajHingani/Capstone-Project-.git', branch: 'main'
   }
  }
  stage('Restore packages'){
   steps{
      bat "dotnet restore ABC_Healthcare\\HealthCare.csproj"
     }
  }
  stage('Clean'){
    steps{
        bat "dotnet clean ABC_Healthcare\\HealthCare.csproj"
     }
   }
 stage('Build') {
   steps {
    bat 'dotnet build ABC_Healthcare\\HealthCare.sln --configuration Release'
   }
  }
  stage('Test') {
   steps {
    bat 'dotnet test ABC Healthcare.test\\ABC Healthcare.test.csproj --logger:trx'
   }
  }
  stage('Publish'){
     steps{
       bat "dotnet publish ABC_Healthcare\\HealthCare.csproj "
     }
}
 }
}
